### ISSUE TITLE
Zenoh `0.10.1-rc`'s `publisher.delete` has bug

### ISSUE THREAD

**Issue by pojiro** [biyooon-ex/zenohex#16]
The bug is https://github.com/eclipse-zenoh/zenoh/issues/633.
The bug is already fixed by https://github.com/eclipse-zenoh/zenoh/pull/634.

But `0.10.1-rc` doesn't include the commit. So @s-hosoai san, take care about it.

This issue will be closed when updating zenoh version from `0.10.1-rc` to over.

### detail

https://github.com/b5g-ex/zenohex/blob/c20fa03b21544205d53f8b1935df7ba2b565e131/test/zenohex/examples/publisher_test.exs#L53-L60

**Comment by s-hosoai** [comment]
Thank you for your report.
I will update it with the next release of Zenoh.

**Comment by s-hosoai** [comment]
This issue was fixed in PR #47
